### ISSUE TITLE
服务器菜单bug

### ISSUE THREAD

**Issue by xianyulaoma** [Maklith/Ncharge#5]
从容器中提取 可以将菜单内物品拿出

**Comment by Maklith** [comment]
目前有4种解决方案
1.删除快捷操作的mod
2.删除菜单
3.等待mod更新
4.等待菜单插件更新

**Comment by Maklith** [comment]
5.不管
6.将菜单内的物品换成毫无价值的物品

**Comment by liyuanchen1996** [comment]
替换成毫无价值的东西 比如染色玻璃这种，直接让拿出来变得无意义就好了。我建议6.

**Comment by Maklith** [comment]
麻烦提交者，说一下自己的建议，感谢

**Comment by 1178406773** [comment]
替换菜单内高价值物品

**Comment by Maklith** [comment]
感谢反馈，最终解决方案为⑥
