### ISSUE TITLE
服务器沉浸工程斗轮机不工作

### ISSUE THREAD

**Issue by liyuanchen1996** [Maklith/Ncharge#6]
如题，斗轮机在地皮无法工作，确认有电，红石信号正常。

**Comment by Maklith** [comment]
建议取消在斗轮机的ftb区块声明

**Comment by liyuanchen1996** [comment]
> 建议取消在斗轮机的ftb区块声明

经过测试，ftb区块声明与否，斗轮机均不工作，单机测试工作良好。

**Comment by Maklith** [comment]
是否在取消后，重新搭建结构

**Comment by liyuanchen1996** [comment]
> 是否在取消后，重新搭建结构

一开始就没有声明区块。是不是region存在旧伤。

**Comment by Maklith** [comment]
抱歉，请等待腐竹获取更多信息
