### ISSUE TITLE
连接服务器时偶尔出现的问题

### ISSUE THREAD

**Issue by AGmouse** [Maklith/Ncharge#8]
![无法加入服务器问题](https://user-images.githubusercontent.com/102458989/160272857-ef5aab29-4002-4167-850f-779fb18e4135.jpg)
![图片](https://user-images.githubusercontent.com/102458989/160272877-4528e1e0-a4f5-405b-b149-e27d22f2ca4d.png)

**Comment by Maklith** [comment]
给个debug
